/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package PreciousPhotographyShop.start;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;


// check in localhost:8080
// https://stackoverflow.com/questions/11345193/gradle-does-not-find-tools-jar
// if run from the JAR file, Spring will run in the background.
// you will need to kill the java subprocess of the terminal to shut Spring down
@SpringBootApplication
public class Main {
    public static void main(String[] args) {
        SpringApplication.run(Main.class, args);
        System.out.println("Program started");
    }
}
