/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package PreciousPhotographyShop;

import PreciousPhotographyShop.databaseInterface.BadExampleDatabase;
import PreciousPhotographyShop.databaseInterface.DatabaseInterface;
import PreciousPhotographyShop.databaseInterface.RealDatabaseInterface;
import PreciousPhotographyShop.model.Photograph;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class Main {
    /*
    Look at this: any part of the program can access the database interface
    through Main.DATABASE, without needing to know exactly which implementation
    is used, so we can easilly swap between implementations by simply changing
    this file.
    */
    public static final DatabaseInterface DATABASE = new RealDatabaseInterface();
    
    public static void main(String[] args) {
        SpringApplication.run(Main.class, args);
        System.out.println("Program started");
        
        try {
            BufferedImage buff = ImageIO.read(new File("C:\\Users\\Matt\\Pictures\\batmanParametric.jpg"));
            DATABASE.storePhotograph(new Photograph("Test photo", buff, "01010100", new String[]{"test"}));
        } catch (IOException ex) {
            ex.printStackTrace();
        }
        
    }
}
